CREATE TABLE TB_PESSOA (
	CODIGO BIGINT PRIMARY KEY NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	TIPO_PESSOA CHAR(1) NOT NULL,
	EMAIL VARCHAR(150) NOT NULL,
	SITE VARCHAR(200),
	CLIENTE CHAR(1) NOT NULL,
	FORNECEDOR CHAR(1) NOT NULL,
	COLABORADOR CHAR(1) NOT NULL,
	TRANSPORTADORA CHAR(1) NOT NULL
);

CREATE SEQUENCE SEQ_PESSOA START WITH 1 INCREMENT BY 1;